version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: apicrm_mysql_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crm_db
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  fastapi:
    build: .
    container_name: apicrm_fastapi_app
    depends_on:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: crm_db
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
